### ISSUE TITLE
Load data error

### ISSUE THREAD

**Issue by rsggsr** [icbi-lab/scirpy#111]
Hi,

I just found this interesting tool based on scanpy! Previously we dig with our scRNAseq data in Seurat and with PAGA for pseudotime. We need further for the immune part and found this may be useful.

However, I encounter some problems even just try to see how this tool performs. While I try to follow the tutorial but fail importing data example (dataswts.wu2020_3k()). Please see below. It would wonderful to solve this problem. Thanks in advance! 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-031ada0ebf4a> in <module>
----> 1 adata = ir.datasets.wu2020_3k()

~\Miniconda3\envs\project\lib\site-packages\scirpy\datasets\__init__.py in wu2020_3k()
     65     filename = settings.datasetdir / "wu2020_3k.h5ad"
     66     with _monkey_patch_tqdm():
---> 67         adata = read(filename, backup_url=url)
     68     return adata

~\Miniconda3\envs\project\lib\site-packages\scanpy\readwrite.py in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, **kwargs)
     95             filename, backed=backed, sheet=sheet, ext=ext,
     96             delimiter=delimiter, first_column_names=first_column_names,
---> 97             backup_url=backup_url, cache=cache, **kwargs,
     98         )
     99     # generate filename and read to dict

~\Miniconda3\envs\project\lib\site-packages\scanpy\readwrite.py in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, suppress_cache_warning, **kwargs)
    497     if ext in {'h5', 'h5ad'}:
    498         if sheet is None:
--> 499             return read_h5ad(filename, backed=backed)
    500         else:
    501             logg.debug(f'reading sheet {sheet} from file {filename}')

~\Miniconda3\envs\project\lib\site-packages\anndata\readwrite\read.py in read_h5ad(filename, backed, chunk_size)
    445     else:
    446         # load everything into memory
--> 447         constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
    448         X = constructor_args[0]
    449         dtype = None

~\Miniconda3\envs\project\lib\site-packages\anndata\readwrite\read.py in _read_args_from_h5ad(adata, filename, mode, chunk_size)
    500     if not backed:
    501         f.close()
--> 502     return AnnData._args_from_dict(d)
    503 
    504 

~\Miniconda3\envs\project\lib\site-packages\anndata\core\anndata.py in _args_from_dict(ddata)
   2155             if d_true_keys[true_key] is not None:
   2156                 for key in keys:
-> 2157                     if key in d_true_keys[true_key].dtype.names:
   2158                         d_true_keys[true_key] = pd.DataFrame.from_records(
   2159                             d_true_keys[true_key], index=key)

AttributeError: 'dict' object has no attribute 'dtype'

**Comment by grst** [comment]
Hi @rsggsr, 

thanks a lot for reporting this! 

I suspect that you use an older version of `anndata` and/or `scanpy` than I used for generating the dataset. Can you please try to update?

```
pip install --upgrade scanpy anndata
```

or 

```
conda upgrade scanpy anndata
```
should do the trick. 


If that is the case, I should update the minimal version requirements accordingly.

**Comment by rsggsr** [comment]
Hi @grst ,

Thanks! It works!

But I just found out that the tool was designed for VDJ sequencing (scTCRseq) but not for simple scRNAseq data. Since actually we only got scRNAseq data, so this one maybe too fancy to us. But do you think like computational one (I found one shown below) would help us? Thanks!

Single-cell TCRseq: paired recovery of entire T-cell alpha and beta chain transcripts in T-cell receptors from singlecell RNAseq, 2016

**Comment by grst** [comment]
If you have scRNA-seq data where the full-length transcript has been captured (e.g. Smart-seq2) you can use [TraCeR](https://github.com/Teichlab/tracer) to reconstruct the VDJ information and 
load the results into `scirpy`. You can use this [nextflow pipeline](https://github.com/nf-core/smartseq2) to process the data. 

If you have 10x data without VDJ information, there's (to my knowledge) no way to recover it.

**Comment by rsggsr** [comment]
Hi, @grst,

We used CellRanger 10X data....
But still thanks for your time! It's a cool tool and easy-to-follow tutorial.

**Comment by grst** [comment]
Too bad :/

Anyway, thanks for reporting the data-loading issue. I now updated the minimal version requirements (#112), s.t. other users should not  encounter this problem any more.
