### ISSUE TITLE
scirpy.read_10x_vdj(path, filtered=True)

### ISSUE THREAD

**Issue by taopeng1100** [icbi-lab/scirpy#121]
Hi I like to read multiple "filtered_contig_annotations.csv" files from 10x; how can I do this in scirpy.read_10x_vdj?

Thx,

Tao

**Comment by grst** [comment]
Hi Tao, 

you can read them in a loop and concatenate them. 
It works the same way as for `adata` files without TCR information, see the solution here: 
https://github.com/theislab/scanpy/issues/267

Hope that helps and let me know if you have further problems! 

Best, 
Gregor

**Comment by taopeng1100** [comment]
Thx! I will try it.

**Comment by JLTrincado** [comment]
Dear authors,

I'm using the solution proposed here for loading multiple 10x vdj files. For some reason, after concatenating some cells loses information. Here I load 2 files and concatenate them. Prior to concatenation, the shown cell has TRA_1_cdr3 region. After concatenating, the region has disappeared. What am I missing?


![image](https://user-images.githubusercontent.com/23315833/80968488-55ea5000-8e18-11ea-8756-acd309dd1c13.png)

Thanks for your help.
Juan L.

**Comment by grst** [comment]
Hi Juan, 

could it be just the order of columns? 
The concatenation seems to sort columns alphabetically, s.t. the `TRB_1_cdr3` column is hidden in the middle (`...`) or the pandas data frame. 

Best, 
Gregor

**Comment by JLTrincado** [comment]
Hi again,

thanks for the quick reply. It wasn't because of the order in the columns, but thanks to that I realize it was my bad when calculating the TCR neighbors. I was using receptor_arms="all" instead of "any". That's why this cell didn't show up as clone.

Thanks again and congratulations for your work.
Best.

**Comment by grst** [comment]
@taopeng1100, I will close this now. Let me know if you have further issues.
