### ISSUE TITLE
Only getting distances 0's or 1's when using cutoff<100 while using the Distance Calculators

### ISSUE THREAD

**Issue by sheetalgiri** [icbi-lab/scirpy#163]
I wanted to calculate the minimum distance for going from samples in one dataset to another. Is there something I'm doing wrong or should I use a higher cutoff? Or a better way to do what I want to do?

**Comment by grst** [comment]
Hi @sheetalgiri, 

I suspect you are using the `identity` metric. This metric will ignore the cutoff. 

Try setting `metric='alignment'` for getting a BLOSUM62-based distance, or `levenshtein` for the edit-distance. 

Cheers, 
Gregor

**Comment by sheetalgiri** [comment]
Thanks for replying @grst . I'm actually getting this result also when I try to use the alignment metric. In the documentation for it, you tell that a cutoff>14 is not a good idea. For me, this metric only seems to return anything other than 0 or 1's for cutoff>100

**Comment by grst** [comment]
What kind of data is this? Your sequences are significantly longer than the usual CDR3 sequences, which are ~10-17aa. 

With longer sequences, higher cutoff values may make sense. The sequences do look quite different, so they for sure won't have an alignment distance < 14, therefore they receive a distance of 0 ("no edge in graph"). 

The definition of the alignment distance is documented [here](https://icbi-lab.github.io/scirpy/generated/scirpy.tcr_dist.AlignmentDistanceCalculator.html#scirpy.tcr_dist.AlignmentDistanceCalculator), it will help you to find an appropriate cutoff for your purpose.

**Comment by sheetalgiri** [comment]
thanks for pointing that out. it seems that the sequences being of different lengths is also making a difference. I just checked and noticed the sequences are length 28 on average, the shortest is of length 17 and longest of length 50!
