### ISSUE TITLE
Loading scBCRseq data

### ISSUE THREAD

**Issue by crushseven-7** [icbi-lab/scirpy#173]
I am handling scTCRseq and scBCRseq at the same time. `scirpy` is a really friendly package for integrated scRNAseq and scTCRsesq. But I can not combine scBCRseq data with scRNAseq, cause it filtered IG gene durning combine two object. Is there a plan for compatibility with scBCRseq data?

**Comment by grst** [comment]
Hi @crushseven-7, 

yes, we are working on it! 
Feel free to join the discussion at https://github.com/icbi-lab/scirpy/issues/132. 

In particular I'd appreciate comments on the naming conventions and would be glad about hints for suitable publicly available demo datasets with BCR data (combined BCR/TCR would be awesome, too).
