### ISSUE TITLE
chain_qc function missing in v0.4.2?

### ISSUE THREAD

**Issue by slukowski** [icbi-lab/scirpy#209]
Hi
I was working through the Wu 2020 3k example dataset with scirpy v0.4.2 and came across an issue at the chain_qc step.
`ir.tl.chain_qc(adata)` where the error is `module 'scirpy._tools' has no attribute 'chain_qc'` 

When I look at the tool function list, chain_qc is not present. I'm wondering if it has it been replaced with another function, or renamed? How critical is the output of that qc to the analysis?

Cheers
Sam

**Comment by grst** [comment]
Sorry, the latest doc is already for v0.5 which I'm gonna release within the next days. 

The docs for 0.4.2 are available here: 
https://icbi-lab.github.io/scirpy/tags/v0.4.2/

The corresponding function in v0.4 is `ir.tl.chain_pairing`. 

Best, 
Gregor

**Comment by slukowski** [comment]
fantastic - thanks Gregor
