### ISSUE TITLE
Annotation of MAIT cells

### ISSUE THREAD

**Issue by FFinotello** [icbi-lab/scirpy#214]
Identification of MAIT cells based on conserved [TCR alpha chains](http://www.cbs.dtu.dk/services/MAIT_Match/MAIT_DB_update.php) (could be done by identity or similarity).

**Comment by grst** [comment]
This seems rather specific, so I'm not sure if this should be a dedicated function. 

It is already pretty straightforward using [`sequence_dist`](https://icbi-lab.github.io/scirpy/generated/scirpy.ir_dist.sequence_dist.html#scirpy.ir_dist.sequence_dist). 

But maybe this could be combined into a generic function together with https://github.com/icbi-lab/scirpy/issues/54.

**Comment by FFinotello** [comment]
Good idea! The list of invariant TCR alpha chain would be needed to annotate the cells with exact matches, but the clonotype network could then be used to link them to additional cell types with similar TCR.

**Comment by grst** [comment]
Closed in favor of #54.
