### ISSUE TITLE
Repertoire overlap seemingly invariant to clonotype network changes

### ISSUE THREAD

**Issue by ktpolanski** [icbi-lab/scirpy#215]
Hello,

I just tried analysing some VDJ data with the package, and encountered some unusual behaviour. I mimicked the tutorial's syntax for calling clonotypes via nucleotide identity and amino acid alignment, and tried to use the results to assess repertoire overlap.

```
ir.pp.ir_neighbors(adata)
ir.tl.define_clonotypes(adata)
ir.tl.clonotype_network(adata, min_size=2)
ir.pl.clonotype_network(adata, color="Donor")
ir.tl.repertoire_overlap(adata, "ind_loc")
ir.pl.repertoire_overlap(adata, "ind_loc", heatmap_cats=["Donor", "Spatial_code"])

ir.pp.ir_neighbors(
    adata,
    metric="alignment",
    sequence="aa",
    cutoff=15,
    receptor_arms="all",
    dual_ir="all",
)
ir.tl.define_clonotype_clusters(
    adata, partitions="connected", sequence="aa", metric="alignment", within_group=None
)
ir.tl.clonotype_network(adata, min_size=4, sequence="aa", metric="alignment")
ir.pl.clonotype_network(adata, color="Donor")
ir.tl.repertoire_overlap(adata, "ind_loc")
ir.pl.repertoire_overlap(adata, "ind_loc", heatmap_cats=["Donor", "Spatial_code"])
```

The two networks come out looking quite different:

![image](https://user-images.githubusercontent.com/14993986/98278147-1865ab80-1f90-11eb-83ff-796298535421.png)
![image](https://user-images.githubusercontent.com/14993986/98278193-287d8b00-1f90-11eb-8593-1f2de221e436.png)

However, in both cases, I get an identical repertoire overlap plot, seemingly derived from the first one?

![image](https://user-images.githubusercontent.com/14993986/98278329-5793fc80-1f90-11eb-911e-a50548e9c800.png)

I can't seem to find any parameters controlling `repertoire_overlap()` in a manner analogous to `clonotype_network()`. According to the documentation entry for `define_clonotypes()` and `define_clonotype_clusters()`, they both save their results to  `.obs['clonotype']`, which is `repertoire_overlap()`'s default input. As such, I'm stumped. Some assistance please?

**Comment by grst** [comment]
`define_clonotype_clusters` stores the results to `.obs["ct_cluster_{sequence}_{metric}"]`, so `.obs["ct_cluster_aa_alignment"]` in your case. 

Can you try if `ir.pl.repertoire_overlap(adata, "ind_loc", target_col="ct_cluster_aa_alignment")` gives you the expected result? 

In any case, I should make that behaviour more explicit, possibly by including the `metric` and `sequence` arguments also into the other plotting functions.

**Comment by ktpolanski** [comment]
Yep, my bad, I caught this literally after posting the issue and even tried to delete it. Can confirm this resolved stuff.

If I could make a suggestion, the tutorial goes off at a tangent about alternate ways of calling clonotypes, and then backtracks to the original nucleotide identity calls without much warning. Would be good to add a bit of warning, and possibly instructions how to use these alternate clonotypes in downstream stuff like you just said.

**Comment by grst** [comment]
Thanks for the feedback, I'll try to address that. 
Let's keep this one open to remind me about it ;)

**Comment by ktpolanski** [comment]
In that case, maybe have `define_clonotypes()`/`define_clonotype_clusters()` explicitly print out where they store their output? You could set scanpy verbosity to the relevant level in the package import block at the start, and then when you run the clonotype caller it says something like `Clonotypes stored in .obs['clonotype']` (or whatever is relevant for the call). Adding in an extra function-side line about downstream `target_col` use might be borderline excessive, but including it in immediate downstream tutorial calls, maybe a bit of text in the description paragraph, should hopefully do the trick and wire the response?

**Comment by grst** [comment]
`define_clonotypes` and `define_clontype_clusters` now issue a `INFO` log message where the clonotype info is stored. This is now on the master branch and will be included in the release I plan for end of April.
