### ISSUE TITLE
Is it possible to import normalized counts or UMAP from seurat?

### ISSUE THREAD

**Issue by algarji** [icbi-lab/scirpy#231]
I like using seurat (R) for sc data normalization, visualization and analysis, but I am interested in the scirpy package to analyze the TCR data, as it is very complete and has some advantages respect other similar R packages. I will use 10x genomics in my experiment. I was wondering if it is possible to represent clonotype data from scirpy in UMAPs  from seurat.

I think that seurat normalized counts can be merged easily with TCR data using the merge function of scirpy. But probably the UMAP representation from scanpy is going to be distributed different in space, so I don't know if it is possible to add the UMAP coordinates from the seurat object to the scirpy object, or maybe there is another solution.

**Comment by grst** [comment]
Hi @algarji, 

scanpy stores the umap coordinates in `adata.obsm["X_umap"]`. 
You can manually set those to the coordinates computed by seurat. Then plotting with clonotypes should work. 

Or you can export `adata.obs` after running scirpy and add it back to the Seurat object in R and make the plots there. 

Cheers, 
Gregor

**Comment by algarji** [comment]
Thanks @grst for the quick response. Yes, I will try what you propose on some training data, it seems affordable.

**Comment by GouQiao** [comment]
> Hi @algarji,
> 
> scanpy stores the umap coordinates in `adata.obsm["X_umap"]`. You can manually set those to the coordinates computed by seurat. Then plotting with clonotypes should work.
> 
> Or you can export `adata.obs` after running scirpy and add it back to the Seurat object in R and make the plots there.
> 
> Cheers, Gregor

　HI@grst

I am also interested in using seurat for scRNAseq, but using scirpy for scTCR.
After combining the data of transcriptome and TCR in scirpy, I want to back to seurat for data merge with multiple samples, do Umap and other analysis. But I met problem when I convert h5ad to seurat. I am not sure is this the problem because I add TCR information or not.
Do you know how to solve the switchover from scirpy to seurat?

Thanks.

**Comment by grst** [comment]
Hi @GouQiao, 

how are you importing the `h5ad` object into seurat? There are several ways of doing that and neither way worked flawlessly for me in the past :/

Since all information you need is usually just some annotations in `adata.obs`, a way that should definitely work is to export `adata.obs` to a csv file, and manually load the columns you need into your Seurat object.

Cheers, 
Gregor

**Comment by GouQiao** [comment]
> Hi @GouQiao,
> 
> how are you importing the `h5ad` object into seurat? There are several ways of doing that and neither way worked flawlessly for me in the past :/
> 
> Since all information you need is usually just some annotations in `adata.obs`, a way that should definitely work is to export `adata.obs` to a csv file, and manually load the columns you need into your Seurat object.
> 
> Cheers, Gregor

Hi,
Thanks for your quick reply.
You mean after extracting adata.obs by adata.obs.to_csv, then add obs information by AddMetadata in seurat?

Gou

**Comment by GouQiao** [comment]
> I like using seurat (R) for sc data normalization, visualization and analysis, but I am interested in the scirpy package to analyze the TCR data, as it is very complete and has some advantages respect other similar R packages. I will use 10x genomics in my experiment. I was wondering if it is possible to represent clonotype data from scirpy in UMAPs from seurat.
> 
> I think that seurat normalized counts can be merged easily with TCR data using the merge function of scirpy. But probably the UMAP representation from scanpy is going to be distributed different in space, so I don't know if it is possible to add the UMAP coordinates from the seurat object to the scirpy object, or maybe there is another solution.

HI.
Have you solved the problem?

**Comment by grst** [comment]
> You mean after extracting adata.obs by adata.obs.to_csv, then add obs information by AddMetadata in seurat?

exactely!

**Comment by GouQiao** [comment]
> 

Thanks for reply.
I tried this way, but I could not do PCA or Umap for seurat after this...

**Comment by grst** [comment]
Are you trying to plot PCA and UMAP in Seurat or in Scanpy?
I'm a bit confused, because adding an additional Metadata variable in
seurat shouldn't affect the UMAP or PCA plots at all.

**Comment by GouQiao** [comment]
> 

Maybe I did something wrong. I used addmeta funtion, but I found the characters become NA value. 
If you dont mind, could you share the codes for add scirpy TCR into seurat object? 
Thank you!

adata.obs.to_csv("Thy_scTCR.csv")
Thy_obs<-read.csv("Thy_scTCR.csv")
Thyctl<-AddMetaData(Thyctl,Thy_obs)

                   orig.ident nCount_RNA nFeature_RNA    X is_cell high_confidence multi_chain extra_chains IR_VJ_1_c_call IR_VJ_2_c_call
AAACCTGAGAAACCAT-1     Thymus       5332         2279 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGAGACTTGAA-1     Thymus       1628          984 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGAGATGCCAG-1     Thymus       4978         1996 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGAGCTAGTCT-1     Thymus       1031          678 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGAGGATATAC-1     Thymus        709          504 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGAGTGTTAGA-1     Thymus       1776         1042 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGCAAACCCAT-1     Thymus       2977         1576 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGCAAATACAG-1     Thymus       2384         1435 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGCAAGGTTCT-1     Thymus       1027          756 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>
AAACCTGCACCAGGCT-1     Thymus        998          697 <NA>    <NA>            <NA>        <NA>         <NA>           <NA>           <NA>

**Comment by grst** [comment]
> If you dont mind, could you share the codes for add scirpy TCR into seurat object?
I have never done that myself, as I practically never work with Seurat. 

>  I used addmeta funtion, but I found the characters become NA value.
I would suspect that the cell-barcodes don't match between your csv file and the Seurat object and this is causing the NAs. So maybe you can investigate that
