### ISSUE TITLE
parasail installation issue

### ISSUE THREAD

**Issue by chris-rands** [icbi-lab/scirpy#237]
Great package, thank you! I had `parasail` installation errors like including `RuntimeError: make of automake failed`. Found a workaround in https://github.com/nanoporetech/medaka/issues/108

```
wget https://ont-research.s3-eu-west-1.amazonaws.com/parasail-1.1.17-py2.py3-none-manylinux1_x86_64.whl
pip install parasail-1.1.17-py2.py3-none-manylinux1_x86_64.whl
pip install scirpy
```

**Comment by grst** [comment]
Hi Chris, 

it seems parasail doesn't provide a wheel for linux. Ultimately this needs to be fixed on the parasail side. 
Using bioconda should also resolve the issue. 

I'll leave this open s.t other users can find this workaround easily, and maybe add a note to the docs at some point.
