### ISSUE TITLE
An issue about multichain column 

### ISSUE THREAD

**Issue by lee-kyoungjun** [icbi-lab/scirpy#239]
Hi I'm kyoungjun lee who is new to scirpy.
while i'm loading 'filtered_contig_annotations.csv' by using read_10x_vdj function, i found that the multichain column doesn't always match with the number of pairs of TRA-TRB.
  
![image](https://user-images.githubusercontent.com/55538330/107135649-da39a880-693f-11eb-9abf-ff50a356afcf.png)

Is there any reason that some events are not taken as 'multi_chain' even they have two or more pairs of TRA-TRB?

Thank you
Kyoungjun

**Comment by grst** [comment]
Hi Kyoungjun, 

thanks for reporting. "non-productive" chains don't count, maybe that's the issue?
Otherwise, could you please share all lines from your `filtered_contig_annotations.csv` from one of the affected cells, then I can have a closer look. 

Best, 
Gregor

**Comment by lee-kyoungjun** [comment]
Hi Gregor,

Thank you for immediate reply.
The chains were productive chains according to  'filtered_contig_annotations.csv' file as shown below.
![image](https://user-images.githubusercontent.com/55538330/107165547-99509b00-69f6-11eb-86e8-c0725dfd80e3.png)
![image](https://user-images.githubusercontent.com/55538330/107165564-a077a900-69f6-11eb-89be-f8aea0f19e25.png)

And below file is from converted file through read_10x_vdj, which saying multichain is False.
![image](https://user-images.githubusercontent.com/55538330/107165614-cbfa9380-69f6-11eb-894d-b2a319e4b796.png)

Actually, this is not the only case. there are 3 or 4 more same cases but all of them were not the 'non-productive chain'.
I really appreciate your help.

Thank you
kyoungjun

**Comment by lee-kyoungjun** [comment]
Oh it was my misunderstood.
I didn't see that multichain means there are more than two full chains.
Thank you for your attention Gregor.

Thank you.
kyoungjun
