### ISSUE TITLE
Label filtered contig annotations?

### ISSUE THREAD

**Issue by chris-rands** [icbi-lab/scirpy#242]
When calling `scirpy.io.read_10x_vdj()` with `filtered=False` it might be useful to add a categorical attribute like `adata.obs["has_ir_filtered"]` to distinguish those cells (or perhaps better use the original `is_cell` and `high_confidence` labels)

**Comment by grst** [comment]
good point, this can be combined with https://github.com/icbi-lab/scirpy/pull/241. 
Do you happen to know if these attributes have an equivalent in the AIRR-standard? 

Or maybe @zktuong knows, afaik he has worked with the cellranger AIRR format already?

**Comment by zktuong** [comment]
There's no equivalent standard columns AFAIK but 10x provides the column `is_cell` in its AIRR output, but not the `high_confidence` column.

**Comment by chris-rands** [comment]
Thanks both, my workaround for now is to read twice with `filtered=False` and `filtered=True` and perform a subtraction to label the filtered cells

**Comment by grst** [comment]
I had another look at the 10x AIRR files. It seems they only contain filtered cells anyway, so for the unfiltered ones we would still have to rely on the 10x csv/json files. 

The AIRR files do, however, contain a `is_cell` column (which is non-standard) and a `productive` column (which is standard) and `productive + is_cell = filtered`. As the file is filtered already, the values are all TRUE.

**Comment by grst** [comment]
Hi @chris-rands, 

#241 is now merged into master, a release follows probably end of April. 
I'd be happy about feedback -- If you want to give it a try you can install the development version using
```
pip install git+https://github.com/icbi-lab/scirpy.git@master
```
The docs of the development version are available [here](https://icbi-lab.github.io/scirpy/develop/index.html). 

In #241, I changed the scirpy data structure to use AIRR Rearrangement column names everywhere. The columns `is_cell` and `high_confidence` get now imported by default from 10x data.

**Comment by chris-rands** [comment]
Thanks @grst, sounds great, I'll try to take a look soon. I had good experience with the previous dev iteration you pointed me towards- it scales well with >300K TCRs. BTW #54 would be a really nice feature in my view (although tricky to validate epitope predictions)

**Comment by grst** [comment]
Great! 

> BTW #54 would be a really nice feature in my view (although tricky to validate epitope predictions)

I agree, but not sure when I'll have time to tackle it.

In the meantime, you can build something like that manually using [`sequence_dist`](https://icbi-lab.github.io/scirpy/develop/generated/scirpy.ir_dist.sequence_dist.html#scirpy.ir_dist.sequence_dist) -- it allows you to compute a distance matrix for two arbitrary sets of distances. One could be a column from `adata.obs`, the other a bunch of sequences downloaded from a database.

Maybe you could also drop a note in #54 about which databases you have in mind and what your use-case is. Or if you'd even fancy to make a PR that would be most welcome :)

**Comment by chris-rands** [comment]
@grst with the dev version I'm getting an error while running `ir.tl.clonotype_network(adata)` (note I only have TCR data loaded, no matched RNA-seq)

```
/path/scirpy/io/_util.py in check_wrapper(*args, **kwargs)
     61             for i in check_args:
     62                 _check_anndata_upgrade_schema(args[i])
---> 63             return f(*args, **kwargs)
     64 
     65         return check_wrapper

/path/scirpy/_tools/_clonotypes.py in clonotype_network(adata, sequence, metric, min_cells, min_nodes, layout, size_aware, base_size, size_power, layout_kwargs, clonotype_key, key_added, inplace, random_state)
    554     # Store results or return
    555     if inplace:
--> 556         adata.obsm[f"X_{key_added}"] = coord_df
    557         params_dict["clonotype_key"] = clonotype_key
    558         params_dict["base_size"] = base_size

/path/anndata/_core/aligned_mapping.py in __setitem__(self, key, value)
    149 
    150     def __setitem__(self, key: str, value: V):
--> 151         value = self._validate_value(value, key)
    152         self._data[key] = value
    153 

/path/anndata/_core/aligned_mapping.py in _validate_value(self, val, key)
    210         ):
    211             # Could probably also re-order index if it’s contained
--> 212             raise ValueError(
    213                 f"value.index does not match parent’s axis {self.axes[0]} names"
    214             )

ValueError: value.index does not match parent’s axis 0 names
```

If I do `coord_df = ir.tl.clonotype_network(adata, inplace=False)` I can see additional cell barcodes prefix, but unsure how to fix it
```
coord_df.index
Index(['AAACCTGAGAAGAAGC-1', 'AAACCTGAGCATGGCA-1', 'AAACCTGAGCTCAACT-1',
       'AAACCTGAGTTAGCGG-1', 'AAACCTGCAAACTGTC-1', 'AAACCTGCAATGAATG-1',
       'AAACCTGCACCAGTTA-1', 'AAACCTGCACCTCGTT-1', 'AAACCTGCACGACGAA-1',
       'AAACCTGCATTCTTAC-1',
       ...
       'TTTGGTTGTCAGAAGC-1', 'TTTGGTTGTCGCGAAA-1', 'TTTGGTTTCCCAAGAT-1',
       'TTTGTCAAGCGTAATA-1', 'TTTGTCAAGTGCAAGC-1', 'TTTGTCAAGTTAGCGG-1',
       'TTTGTCACAATGGATA-1', 'TTTGTCACACATTCGA-1-3', 'TTTGTCAGTTTAGGAA-1-1',
       'TTTGTCATCGCCAAAT-1-1'],
      dtype='object', name='cell_id', length=328389)
adata.obsm.dim_names
Index(['AAACCTGAGAAGAAGC-1', 'AAACCTGAGCATGGCA-1', 'AAACCTGAGCTCAACT-1',
       'AAACCTGAGTTAGCGG-1', 'AAACCTGCAAACTGTC-1', 'AAACCTGCAATGAATG-1',
       'AAACCTGCACCAGTTA-1', 'AAACCTGCACCTCGTT-1', 'AAACCTGCACGACGAA-1',
       'AAACCTGCATTCTTAC-1',
       ...
       'TTTGGTTGTCAGAAGC-1', 'TTTGGTTGTCGCGAAA-1', 'TTTGGTTTCCCAAGAT-1',
       'TTTGTCAAGCGTAATA-1', 'TTTGTCAAGTGCAAGC-1', 'TTTGTCAAGTTAGCGG-1',
       'TTTGTCACAATGGATA-1', 'TTTGTCACACATTCGA-1', 'TTTGTCAGTTTAGGAA-1',
       'TTTGTCATCGCCAAAT-1'],
      dtype='object', name='cell_id', length=328389)
```

I'll create a separate issue if needed thanks

I'll drop a note on #54 later

**Comment by grst** [comment]
Thanks for testing and for reporting! Would be great if you could open a separate issue!
