### ISSUE TITLE
Cells without IRs are assigned unique clonotype with size=1

### ISSUE THREAD

**Issue by chris-rands** [icbi-lab/scirpy#243]
I'm integrating 5' RNA-seq and TCR data, works well thanks. One question, `adata[adata.obs["has_ir"] == "False"].obs["clonotype"]` includes unique categories for each cell in the form `"n_5_no IR"`, and `.obs["clonotype_size"]` (and `.obs["clonal_expansion"]`) is `1` for these cells (rather than `0`). This creates a slightly misleading picture if you do `sc.pl.umap(adata, color=["has_ir", "clonotype", "clonal_expansion"])` because unique clonotypes are visulliazed the same as absent clonotypes- could it be handled differently?

**Comment by grst** [comment]
This should be fixed when I finally manage to wrap up #230. 
In the meanwhile, you could just manually set these values to zero before plotting: 

```python
adata.obs.loc[adata.obs["has_ir"] == "False", "clonotype_size"] = 0
```

**Comment by grst** [comment]
clonotype size should behave as expected in the latest dev version. Still an issue with `clonal_expansion`. Working on it.

**Comment by grst** [comment]
Hi @chris-rands,

this should now work in the latest development version. Could you give it a try and check if everything works as expected now?

You can install the development version using
```bash
pip install git+https://github.com/icbi-lab/scirpy.git@master
```

Note that the procedure for calling clonotypes has slightly changed, in particular: 
 * `pp.ir_neighbors` has been replaced by `pp.ir_dist`
 * `tl.define_clonotypes` now takes the `dual_ir` and `receptor_arms` arguments (they were previously provided to `ir_neighbors`)
 * The clonotype network now collapses cells with identical receptors to a single dot

The documentation of the development version is at https://icbi-lab.github.io/scirpy/develop and [this tutorial section](https://icbi-lab.github.io/scirpy/develop/tutorials/tutorial_3k_tcr.html#Define-clonotypes-and-clonotype-clusters) describes the updated clonotype definition.

**Comment by chris-rands** [comment]
Thanks @grst - appreciate these updates and I will check it out soon. On clonotype definitions, how different are your clonotype calls from those defined by cellranger?

**Comment by grst** [comment]
As far as I can tell, cellranger requires all chains of a cells to be identical to be grouped to a clonotype. This behaviour is comparable to `tl.define_clonotypes(receptor_arms="all", dual_ir="all")`. 

Scirpy's default is `receptor_arms="all", dual_ir="any"`, i.e. at least one VJ and at least one VDJ chain need to match.

**Comment by chris-rands** [comment]
Hi @grst , just had a quick look at the development version. It installed smoothly thanks. I've not had a chance to asses the clonotypes yet but a couple of points on usability:
- The new implementation to define clonotypes uses less memory (I was having issues with >100Gb memory used for a large dataset under the old implementation) so that's great
- I can't save the object to .h5ad due to `TypeError: Can't implicitly convert non-string objects to strings` with `Above error raised while writing key 'uns/clonotype/cell_indices' of <class 'h5py._hl.files.File'> from /.` I encountered this with parts of scanpy also, e.g. https://github.com/theislab/scanpy/issues/1651#issuecomment-779382361

Side note, would it be useful to be able to use cellranger's clonotype calls directly with scirpy for 10X data? Obviously it's good to have the sciripy functionality to define clonotypes with control over the parameters etc. but I think many users might be satisfied with the 10X predictions. I'm interested to actually compare them properly time permitting.

**Comment by grst** [comment]
>  * The new implementation to define clonotypes uses less memory (I was having issues with >100Gb memory used for a large dataset under the old implementation) so that's great

great to hear! 

>  * I can't save the object to .h5ad due to `TypeError: Can't implicitly convert non-string objects to strings` with `Above error raised while writing key 'uns/clonotype/cell_indices' of <class 'h5py._hl.files.File'> from /.` I encountered this with parts of scanpy also, e.g. [theislab/scanpy#1651 (comment)](https://github.com/theislab/scanpy/issues/1651#issuecomment-779382361)

Good catch! I probably need to use lists instead of the numpy arrays in `uns`. (I created #257)

> Side note, would it be useful to be able to use cellranger's clonotype calls directly with scirpy for 10X data? Obviously it's good to have the sciripy functionality to define clonotypes with control over the parameters etc. but I think many users might be satisfied with the 10X predictions. I'm interested to actually compare them properly time permitting.

As long as they are stored in a column in `obs` it should be possible to use them in most scirpy functions by specifying the clonotype column. Clonotype network plots won't work, though, as they require the network computed by `define_clonotypes`. 
With #241, 10x clonotypes should already get read in from cellranger AIRR files, maybe it's worth adding an option to read them in from csv and json files as well. But that only makes sense after #241 is merged as it changes quite a lot in the IO logic. 

For now, you could just add them from the cellranger `csv` files by doing a pandas merge on `obs`. If you compare them to the scirpy clonotypes, please share the result! I would be happy to add a note to the documentation about it!
