### ISSUE TITLE
scirpy to analyze BCR

### ISSUE THREAD

**Issue by QuKunLab** [icbi-lab/scirpy#245]
could scirpy be applied to analyze scBCR data? what's the potential risk?

**Comment by grst** [comment]
Sure, that's entirely possible. The procedure is analogous to the TCR tutorial, but you might want to consider the [`hamming`](https://icbi-lab.github.io/scirpy/generated/scirpy.ir_dist.HammingDistanceCalculator.html#scirpy.ir_dist.HammingDistanceCalculator) distance for clonotype networks. 

You can also take a look at [dandelion](https://github.com/zktuong/dandelion) which provides additional tools for B cells from the *immcantation* suite. We are currently working on making the transition between dandelion and scirpy more smoothly.

**Comment by grst** [comment]
Hi @QuKunLab, 

I'm cleaning up issues a bit and closing this. Feel free to reopen or create a new issue if you have any other questions :) 

Cheers, 
Gregor
