### ISSUE TITLE
Cells without alpha chain

### ISSUE THREAD

**Issue by nicoac** [icbi-lab/scirpy#246]
Hello! Really enjoying the package. I have a question regarding cells without alpha chains and how they should be interpreted. I have a very large TCR clonotype that is returning without an alpha chain and I'm having a hard time understanding why this would be the case based on the qc steps that were taken.

Results of QC:

![image](https://user-images.githubusercontent.com/61473108/110547369-12720980-80ed-11eb-9846-4a994c0524b4.png)

Clonotype network after ct_cluster_aa_alignment

![image](https://user-images.githubusercontent.com/61473108/110547702-6e3c9280-80ed-11eb-9a0a-6131cd19c772.png)

![image](https://user-images.githubusercontent.com/61473108/110547578-595fff00-80ed-11eb-840d-15b57b5ed484.png)

Any advice or thoughts would be much appreciated!

**Comment by grst** [comment]
Hi @nicoac, 

how did you do the QC filtering? 
Because from your figure, this is totally expected - "Orphan VDJ" refers to cells having a beta chain only.

**Comment by nicoac** [comment]
Now that you've said that I realized I'm not dumping out the orphan VDJ, only the multi-chain. Is it possible to filter those cells as the multi-chain was done here? : adata = adata[adata.obs["multi_chain"] != "True", :].copy(). Is the obs called "orphan_vdj"?

I guess I'm just surprised with how large that clone appears in the clonotype network graph when looking at the bar graph.

**Comment by grst** [comment]
Sure! You can always check the available categories of a column in `obs` with 

```python
adata.obs['chain_pairing'].unique()
```

To filter, you can use, e.g. 
```python
adata = adata[~adata.obs["chain_pairing"].isin(["orphan VDJ", "orphan VJ", "no IR"]), :].copy()
```

(untested, hope there are no typos)

**Comment by grst** [comment]
Closing this for now - feel free to reopen if there are any other questions!

**Comment by nicoac** [comment]
Thanks so much Gregor. Will try this out soon.
