### ISSUE TITLE
Saving plots (png, pdf, svg)

### ISSUE THREAD

**Issue by ivandatasci** [icbi-lab/scirpy#250]
Could a kind soul point me to an example of saving a plot to png?

Its probably somewhere in the documentation but I am unable to find it.

Thank you.

**Comment by grst** [comment]
Hi @ivandatasci, 

every scirpy plotting function returns a matplotib Axes object (or a list of such). 
You can use

```python
axs = ir.pl.clonotype_network(adata, color="patient")
axs[0].get_figure().savefig("plot.pdf")
```

to save those figures.

**Comment by ivandatasci** [comment]
That almost worked. For the sake of helping others, allow me to elaborate.

This is what worked for me

    axs = ir.pl.group_abundance(adata, normalize=False, groupby="chain_pairing", target_col="sample")

    axs.get_figure().savefig('myfigure.pdf', bbox_inches='tight')

Notice the use of simply `axs` as opposed to `axs[0]`.

Also notice the need to indicate `bbox_inches='tight'` so that the figure did not get all four edges cropped out.

Thank you very much @grst. Feel free to close this issue.
