### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by gokceneraslan** [icbi-lab/scirpy#262]
Hi there,

Thanks for this cool package. Just wanted to report that the documentation is outdated regarding the "receptor_arms" parameter:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1140359/115879647-e6e67c80-a417-11eb-9a7b-22d2ad786b1d.png">

**Comment by grst** [comment]
Thanks for reporting! Should be fixed now.
