### ISSUE TITLE
access to v0.6.1 documentation

### ISSUE THREAD

**Issue by leoqiang** [icbi-lab/scirpy#267]
Hello, the dev team of scirpy.

Thank a lot for developing such a nice tools for VDJ seq analysis system. 

We are actively using it. However, I have a problem. With the latest release of v0.7.0, the documentation site is updated accordingly. However, not yet able to update to the latest version, we are still using v0.6.1 version in our analysis. Unfortunately, due to the big changes introduced, the documentation is not compatible with the old ones.

I wonder would it be possible to still provide a place to access the documentation of v0.6.1. I could not find it at https://icbi-lab.github.io/scirpy/api.html. Maybe I missed it...

Many thanks in advances.

Best,
Qiang

**Comment by grst** [comment]
Hi Qiang, 

sorry about the inconvenience, the documentation 0.6.1 is already available here: https://icbi-lab.github.io/scirpy/tags/v0.6.1/. 
But I need to add links to the older versions somewhere.

**Comment by leoqiang** [comment]
Thank you very much for the swift reply.

**Comment by grst** [comment]
I closed this as the docs of the development version now contain a list of previous versions. 

I'll leave this issue pinned until I release the next version and it will be present in the main docs.
