### ISSUE TITLE
Error in scirpy.pp.merge_airr_chains()

### ISSUE THREAD

**Issue by samcwj** [icbi-lab/scirpy#268]
Hi! I'm new to scanpy and scirpy. I've encountered an error while trying to merge 10x 5'GEx, BCR and TCR datasets. The first merge of BCR with 5'GEx using scirpy.pp.merge_with_ir() was successful, but adding on the TCR after that was not. This is the error:

```python
>>> ir.pp.merge_with_ir(IOGex, IOBCR)
... storing 'orig.ident' as categorical
... storing 'SampleID' as categorical
... storing 'Batch' as categorical

>>> ir.pp.merge_airr_chains(IOGex, IOTCR)
WARNING: Non-standard locus name ignored: Multi
WARNING: Non-standard locus name ignored: None
WARNING: Non-standard locus name ignored: Multi
WARNING: Non-standard locus name ignored: None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/samuel_chuah/miniconda3/lib/python3.9/site-packages/scirpy/io/_util.py", line 66, in check_wrapper
    return f(*args, **kwargs)
  File "/home/samuel_chuah/miniconda3/lib/python3.9/site-packages/scirpy/_preprocessing/_merge_adata.py", line 59, in merge_airr_chains
    tmp_cell.update(cell)
  File "/home/samuel_chuah/miniconda3/lib/python3.9/_collections_abc.py", line 856, in update
    self[key] = other[key]
  File "/home/samuel_chuah/miniconda3/lib/python3.9/site-packages/scirpy/io/_datastructures.py", line 113, in __setitem__
    raise ValueError(
ValueError: Cell-level attributes differ between different chains. Already present: `None`. Tried to add `True`.
```

Would appreciate some help in understanding the error! Thank you so much!

**Comment by samcwj** [comment]
> Hi @samcwj,
> 
> thanks for reporting this issue!
> 
> The so-called "cell-level attributes" (rather than attributes specific for one of the four "chains") are, per default, `is_cell`, `high_confidence`.
> I made sure that when merging two datasets, the cell-level attributes need to be consistent.
> 
> Apparently, this is a bit too strict. In your case, I suspect that some cells of one dataset have `is_cell == None` while the same cells in the other dataset have `is_cell == True`.
> 
> I need to think how to best solve this. In the meanwhile, you can probably work around it by explicitly overriding the values for all cells:
> 
> ```python
> IOGex.obs["is_cell"] = "None"
> IOTCR.obs["is_cell"] = "None"
> IOGex.obs["high_confidence"] = "None"
> IOTCR.obs["high_confidence"] = "None"
> ```
> 
> Best,
> Gregor

Thank you so much for the quick reply Gregor! The merging works now!

Maybe just for context, I loaded my BCR and TCR data using the 10x filtered_contig_annotations.csv files, so the columns for "is_cell" and "high_confidence" are all True. My 5'GEx data contains cells other than B and T cells. Perhaps that might be the cause of the labelling is_cell = "None" during the merger. In any case, thank you once again! I will continue exploring these tools.

**Comment by grst** [comment]
Hi @samcwj, 

the issue should be solved in the latest development version. 
You can install it using 

```bash
pip install git+https://github.com/icbi-lab/scirpy.git@master
```

Would be amazing if you could give it a try! 

Cheers, 
Gregor

**Comment by samcwj** [comment]
Hi Gregor!

So sorry for the delayed reply, I have been really busy. It works nicely now! I have merged both BCR and TCR data together with my GEx data. I will have to spend more time making sense of it, but for now, thank you so much for taking the time! Really appreciated!

Samuel

**Comment by grst** [comment]
No worries! Glad it works and LMK if you encounter any other issues!
