### ISSUE TITLE
has_ir: True and None but not False is plotted

### ISSUE THREAD

**Issue by akk01** [icbi-lab/scirpy#269]
![download](https://user-images.githubusercontent.com/25061318/118560063-eb603580-b736-11eb-8abe-c2ea7cb4e375.png)
In this plot, all I could see is True (Blue) and None (Orange), but looking at obs, it also contains False. Should I expect to see all three- True, False and None in the plot. 

`adata_tcr.obs['has_ir'].drop_duplicates()` gives following:

`obs_names`
`AAACCTGAGCGATAGC-1    True`
`Name: has_ir, dtype: category`
`Categories (3, object): ['True', 'False', 'None']`

**Comment by grst** [comment]
Hi @akk01, 

this might have an easy explanation: The `categorical dtype` is prepared to take the values `True`, `None`, `False`, but that doesn't mean that all categories are actually present. 

Can you please report: 

```python
adata.obs["has_ir"].dtype
```

and 

```python
adata.obs["has_ir"].value_counts()
```

Cheers,
Gregor

**Comment by akk01** [comment]
`adata.obs["has_ir"].value_counts()`

True     5308
None     5240
False       0
Name: has_ir, dtype: int64

`adata.obs["has_ir"].dtype`
CategoricalDtype(categories=['True', 'False', 'None'], ordered=False)


Thanks!

**Comment by grst** [comment]
> I am not quite clear that how is None different fro False?

`None` means the IR data does not contain the respective cell at all. `False` means that the IR data
contains the cell, but no productive CDR3 sequences. If I remember correctly, that latter won't occur when working with filtered 10x data.

**Comment by akk01** [comment]
Thansk!
