### ISSUE TITLE
Problems reloading saved h5ad and clonotype networks

### ISSUE THREAD

**Issue by ddemaeyer** [icbi-lab/scirpy#270]
I'm performing an analysis using scirpy in combination with h5ad. After generating the clonotype networks the data is stored on disk. When reloading the data I run into the following error: 

```pytb

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-e8ca1595cded> in <module>
      1 ir.pl.clonotype_network(
----> 2     data, color="Status", base_size=20, label_fontsize=9, panel_size=(20, 20
      3                                                                        )
      4 )

~/.local/lib/python3.7/site-packages/scirpy/io/_util.py in check_wrapper(*args, **kwargs)
     64             for i in check_args:
     65                 _check_anndata_upgrade_schema(args[i])
---> 66             return f(*args, **kwargs)
     67 
     68         return check_wrapper

~/.local/lib/python3.7/site-packages/scirpy/_plotting/_clonotypes.py in clonotype_network(adata, color, basis, panel_size, color_by_n_cells, scale_by_n_cells, base_size, size_power, use_raw, show_labels, label_fontsize, label_fontweight, label_fontoutline, label_alpha, label_y_offset, legend_fontsize, legend_width, show_legend, show_size_legend, palette, cmap, edges_color, edges_cmap, edges, edges_width, frameon, title, ax, fig_kws)
    200 
    201     clonotype_res = adata.uns[clonotype_key]
--> 202     coords, adj_mat = _graph_from_coordinates(adata, clonotype_key)
    203     nx_graph = nx.Graph(_distance_to_connectivity(adj_mat))
    204 

~/.local/lib/python3.7/site-packages/scirpy/_tools/_clonotypes.py in _graph_from_coordinates(adata, clonotype_key)
    598 
    599     # Networkx graph object for plotting edges
--> 600     adj_mat = clonotype_res["distances"][coords["dist_idx"].values, :][
    601         :, coords["dist_idx"].values
    602     ]

/opt/conda/lib/python3.7/site-packages/scipy/sparse/_index.py in __getitem__(self, key)
     31     """
     32     def __getitem__(self, key):
---> 33         row, col = self._validate_indices(key)
     34         # Dispatch to specialized methods.
     35         if isinstance(row, INT_TYPES):

/opt/conda/lib/python3.7/site-packages/scipy/sparse/_index.py in _validate_indices(self, key)
    135                 row += M
    136         elif not isinstance(row, slice):
--> 137             row = self._asindices(row, M)
    138 
    139         if isintlike(col):

/opt/conda/lib/python3.7/site-packages/scipy/sparse/_index.py in _asindices(self, idx, length)
    166         # Check bounds
    167         max_indx = x.max()
--> 168         if max_indx >= length:
    169             raise IndexError('index (%d) out of range' % max_indx)
    170 

TypeError: '>=' not supported between instances of 'str' and 'int'
```

I tried regenerating the identity network, but this results in the same error. Any ideas?

KR 
Dries

**Comment by grst** [comment]
Hi @ddemaeyer, 

thanks for reporting this! 
Can you please provide the versions of all packages? 

```python
import scanpy as sc
sc.logging.print_versions()
```

**Comment by ddemaeyer** [comment]
```
print(sc.__version__)
print(ir.__version__)

1.6.0
0.7.0
```

Update to 1.7.2 first and then see? Or will I best rerun the clonotyping (painful since this is 5 hours compute)?

**Comment by ddemaeyer** [comment]
Reloading using 1.7.2 remains the same, I will restart the scirpy analysis with a 1.7.2 environment and see what happens when redoing the save and reload.

**Comment by grst** [comment]
Can you please report the `dtypes` of all columns in `adata.obsm["X_clonotype_network"]`? 

e.g. 
```python
for col in adata.obsm["X_clonotype_network"].columns:
    print(col, adata.obsm["X_clonotype_network"][col].dtype)
```

It seems something gets saved as `str` while it should be `int`. I also believe that simply rerunning `tl.clonotype_network` should be enough, no need to redo the clonotype definition.

**Comment by ddemaeyer** [comment]
I have been looking as well, but this seems to be ok 

```
data.obsm["X_clonotype_network"].dtypes
x    float64
y    float64
dtype: object
```

**Comment by grst** [comment]
I've been sloppy... the offending column is `dist_idx` in the [aggregated dataframe](https://github.com/icbi-lab/scirpy/blob/0f0b28243ee9db5e0bf1ffac24d78dbed83cb628/scirpy/_tools/_clonotypes.py#L589). Which [originates from](https://github.com/icbi-lab/scirpy/blob/0f0b28243ee9db5e0bf1ffac24d78dbed83cb628/scirpy/_tools/_clonotypes.py#L577-L582) `adata.uns[<clonotype_key>]["cell_indices"]`. 

Could you please check that as well?

**Comment by ddemaeyer** [comment]
The keys are indeed strings instead of ints

I did `data.uns["clone_id"]["cell_indices"] = {int(k):v for k,v in data.uns["clone_id"]["cell_indices"].items()}`, however the problem remains.

**Comment by grst** [comment]
I think it's an issue with how `h5py` serializes dicts. I'll look into that...
One last thing: what's your version of `h5py`?

**Comment by grst** [comment]
Hi @ddemaeyer, 


the issue should be solved in the latest development version. 
You can install it using 

```bash
pip install git+https://github.com/icbi-lab/scirpy.git@master
```

Would be amazing if you could give it a try! 

Cheers, 
Gregor

**Comment by ddemaeyer** [comment]
Confirmed resolved, loading the exact same dataset works now (y)
