### ISSUE TITLE
Additional TCR diversity metrics besides alpha_diversity?

### ISSUE THREAD

**Issue by naity** [icbi-lab/scirpy#276]
Hi scirpy team,

I was wondering if more TCR diversity metrics such as inverse Simpson index could be added to scirpy in addition to alpha_diversity? Thanks very much!

**Comment by grst** [comment]
Hi @naity, 

thanks for the suggestions! 

It should be rather easy to support [these additional metrics](http://scikit-bio.org/docs/0.4.2/generated/skbio.diversity.alpha.html#module-skbio.diversity.alpha) by relying on scikit-bio. Would that suit your needs? 

One additional challenge with single-cell data is that some of the metrics strongly depend on the number of cells per sample (e.g. shannon entropy would mostly reflect then number of cells rather than the complexity of the repertoire, which is why we use the "normalized shannon entropy" in scirpy. 

Cheers, 
Gregor

**Comment by naity** [comment]
Yes, that would be very useful! There are additional metrics such as D50 and hill numbers, which I didn't find on scikit-bio but are supported by packages like immunarch (https://immunarch.com/reference/repDiversity.html). Thank you!

**Comment by naity** [comment]
Hi @grst,

I have modified the `alpha_diversity` function to include a version of the D50 metric as below. Would you be interested in this? If so, I would be happy to contribute more and potentially submit a PR:

```
@_check_upgrade_schema()
def alpha_diversity(
    adata: AnnData,
    groupby: str,
    *,
    target_col: str = "clone_id",
    method: str = "normalized shannon entropy",
    inplace: bool = True,
    key_added: Union[None, str] = None,
) -> pd.DataFrame:
    """Computes the alpha diversity of clonotypes within a group.

    Uses the `Shannon Entropy <https://mathworld.wolfram.com/Entropy.html>`__ as
    diversity measure. The Entrotpy gets
    `normalized to group size <https://math.stackexchange.com/a/945172>`__.

    Ignores NaN values.

    Parameters
    ----------
    adata
        Annotated data matrix
    groupby
        Column of `obs` by which the grouping will be performed.
    target_col
        Column on which to compute the alpha diversity
    inplace
        If `True`, add a column to `obs`. Otherwise return a DataFrame
        with the alpha diversities.
    key_added
        Key under which the alpha diversity will be stored if inplace is `True`.
        Defaults to `alpha_diversity_{target_col}`.

    Returns
    -------
    Depending on the value of inplace returns a DataFrame with the alpha diversity
    for each group or adds a column to `adata.obs`.
    """
    # Could rely on skbio.math if more variants are required.
    def _shannon_entropy(freq):
        """Normalized shannon entropy according to
        https://math.stackexchange.com/a/945172
        """
        if len(freq) == 1:
            # the formula below is not defined for n==1
            return 0
        else:
            return -np.sum((freq * np.log(freq)) / np.log(len(freq)))
    
    def _dxx(freq, perc, normalize=True):
        """
        DXX: minimum number of clonotypes that account for XX% of the cell population.
        If normalize, further divided by the total number of unique clonotypes
        """
        freq = freq.sort_values(ascending=False)
        prop, i = 0, 0
        
        while (prop < perc):
            prop += freq[i]
            i += 1

        if normalize:
            i /= len(freq)

        return i

    ir_obs = adata.obs.loc[~_is_na(adata.obs[target_col]), :]
    clono_counts = (
        ir_obs.groupby([groupby, target_col], observed=True)
        .size()
        .reset_index(name="count")
    )

    diversity = dict()
    for k in sorted(ir_obs[groupby].unique()):
        tmp_counts = clono_counts.loc[clono_counts[groupby] == k, "count"].values
        tmp_freqs = tmp_counts / np.sum(tmp_counts)

        np.testing.assert_almost_equal(np.sum(tmp_freqs), 1)

        if method == "normalized shannon entropy":
            diversity[k] = _shannon_entropy(tmp_freqs)
        elif method == "D50":
            diversity[k] = _dxx(tmp_freqs, perc=0.5)

    if inplace:
        key_added = "alpha_diversity_" + target_col if key_added is None else key_added
        adata.obs[key_added] = adata.obs[groupby].map(diversity)
    else:
        return pd.DataFrame().from_dict(diversity, orient="index")
```

**Comment by grst** [comment]
PR would be cool! 
I can then finalize it and also add the skbio metrics (or feel free to add those yourself, if you feel like :) )

**Comment by chris-rands** [comment]
+1 for the gini index as applied here https://www.nature.com/articles/s41591-021-01329-2

**Comment by naity** [comment]
> +1 for the gini index as applied here https://www.nature.com/articles/s41591-021-01329-2
> 
> Edit: sorry I jumped in. Anyway, testing similar approach, also need to modify the plotting function to add the `method` arg

Great point, thanks Chris! It would be great if we could collaborate on this!

**Comment by naity** [comment]
Hi @grst,

I submitted a PR to include D50 and `skbio`'s diversity metrics, and `normalized shannon entropy` is still the default. Would love to hear your thoughts.

Thanks very much!
