### ISSUE TITLE
Compatibility with Cell Ranger 6

### ISSUE THREAD

**Issue by vladie0** [icbi-lab/scirpy#279]
Dear developers, 

the new release of cell ranger incooporated some changes in the annotation of the contig files. 

contig csv header cell ranger 5.X:
barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,cdr3,cdr3_nt,reads,umis,raw_clonotype_id,raw_consensus_id

contig csv header cell ranger 6.X 
barcode	is_cell	contig_id	high_confidence	length	chain	v_gene	d_gene	j_gene	c_gene	full_length	productive	fwr1	fwr1_nt	cdr1	cdr1_nt	fwr2	fwr2_nt	cdr2	cdr2_nt	fwr3	fwr3_nt	cdr3	cdr3_nt	fwr4	fwr4_nt	reads	umis	raw_clonotype_id	raw_consensus_id	exact_subclonotype_id

This implies that the import module is not populating some columns properly for cellranger 6.X files, would you be able to provide support for Cell Ranger 6.X?

**Comment by grst** [comment]
Hi @vladie0, 

thanks for pointing that out, I'll look into it. 
Shouldn't cellranger by now also output AIRR files? Have you tried those with `read_airr`? 

Cheers, 
Gregor

Note to self: example files are available at https://www.10xgenomics.com/resources/datasets/integrated-gex-and-vdj-analysis-of-connect-generated-library-from-mouse-pbmcs-

**Comment by grst** [comment]
Using the example files, the import works for me without error. So you would like scirpy to also import the additional columns (`fwr_{1,2,3,4}{,_nt}`, `cdr_{1,2}{,_nt}`)? Or am I missing something different?
