### ISSUE TITLE
TRAV/DV rearrangements

### ISSUE THREAD

**Issue by zktuong** [icbi-lab/scirpy#285]
hey @grst, this was alerted to me:

_Since the TRD locus is embedded in the TRA locus, a few TRAV genes have been found rearranged, not only as expected to TRAJ but also to TRDD-TRDJ genes. The first five Homo sapiens TRAV genes found in that case received the designation TRAV/DV (this does not exclude that other TRAV genes may be found occasionally rearranged to TRDD-TRDJ). They include Homo sapiens TRAV14/DV4, TRAV29/DV5, TRAV23/DV6, TRAV36/DV7 and TRAV38-2/DV8 genes._(http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=genetable&species=human&group=TRAV)

So currently, the infer locus code would not catch this:
https://github.com/icbi-lab/scirpy/blob/f0599abecc93c7db9ae1b0db268018d534ffe6da/scirpy/io/_io.py#L444-L472

These genes would be annotated with `TRA` locus, even after reassignment with igblastn. While not really an issue for TRA chains, it poses an issue for `TRD` chains because it seems `AirrCell` will drop the `d_call` from the affected contig, and wrongly assign it to `IR_VJ` columns rather than `IR_VDJ`:
![image](https://user-images.githubusercontent.com/26215587/127767846-a6363864-587f-4c28-a855-e0ba61dc437f.png)

I suppose something to catch it like this may work:
```python
queries = [q for q in [d_call, j_call, c_call] if pd.notnull(q)]
if re.search('TRAV.*/DV', v_call):
    if all([re.search('TRA', x) for x in queries])
        locus = 'TRA'
    elif all([re.search('TRD', x) for x in queries]) 
        locus = 'TRD'
```

**Comment by grst** [comment]
Thanks for letting me know! I'll look into it, but hopefully it shouldn't affect too many people anyway as most formats provide a `locus` annotation directly.

**Comment by grst** [comment]
#288 should address this, maybe you can have a quick look at the PR. 

I wonder if there are more such caveats?
