### ISSUE TITLE
clonotype_modularity function?

### ISSUE THREAD

**Issue by algarji** [icbi-lab/scirpy#295]
Hello, I am not very familiar to python, but I am trying to use scirpy to analyse some 10x TCR data. Everything worked quite good for me, but I can't run one of the most interesting options: ir.tl.clonotype_modularity(). I obtain the following error:
`ir.tl.clonotype_modularity(adata, target_col="cc_aa_alignment")`
Traceback (most recent call last):
  File "<ipython-input-96-8e57d564c99f>", line 1, in <module>
    ir.tl.clonotype_modularity(adata, target_col="cc_aa_alignment")
AttributeError: module 'scirpy._tools' has no attribute 'clonotype_modularity'

Maybe this function changes its name in some release or something? Thank you

**Comment by grst** [comment]
The clonotype_modularity function is really new. Are you using the latest
version of scirpy?

**Comment by algarji** [comment]
Yes, you were right @grst , I was using an old scirpy version. However, I updated scirpy and scanpy and I still got an error:
`ir.tl.clonotype_modularity(adata, target_col="cc_aa_alignment")`
```
Traceback (most recent call last):

  File "<ipython-input-81-8e57d564c99f>", line 1, in <module>
    ir.tl.clonotype_modularity(adata, target_col="cc_aa_alignment")

  File "C:\Users\algar\anaconda3\lib\site-packages\scirpy\_tools\_clonotype_modularity.py", line 114, in clonotype_modularity
    adata.obsp[connectivity_key][na_mask, :][:, na_mask],

  File "C:\Users\algar\anaconda3\lib\site-packages\anndata\_core\aligned_mapping.py", line 148, in __getitem__
    return self._data[key]

KeyError: 'connectivities'
```

Maybe my problem should be that connectivities is not stored in adata.obsp. I read that this could be because my anndata file is not in the newest version or something and connectivities can be stored in adata.uns inside neighbors. 
`adata.uns.keys()`
`odict_keys(['sample_colors', 'complex_colors', 'has_ir_colors', 'chain_pairing_colors', 'ir_dist_nt_identity', 'clone_id', 'clonotype_network', 'ir_dist_aa_alignment', 'cc_aa_alignment', 'clonal_expansion_colors', 'rank_genes_groups'])`

However, neighbors is in overloaded keys and I don't know how to get access to connectivities in this format and move it to adata.obsp:
`adata.uns.overloaded.keys()`
`dict_keys(['neighbors'])`

Any idea on how to solve this problem? Sorry for the inconvenience and thank you.

**Comment by grst** [comment]
Can you try to re-run `scanpy.pp.neighbors` before running `clonotype_modularity`?

**Comment by algarji** [comment]
Yes, that definitely worked. Thank you so much, and congrats for such an amazing package @grst
