### ISSUE TITLE
Does scirpy use dim reductions to learn clonotypes? - Critical differences between results on full Wu data

### ISSUE THREAD

**Issue by davisidarta** [icbi-lab/scirpy#313]
Hi! Thank you for developing this great library! 

I'm analyzing the Wu dataset as [provided](https://icbi-lab.github.io/scirpy-paper/wu2020.html) for Scirpy's manuscript. I'm using new dimensionality reduction methods and found a strikingly higher diversity of T cells in numerous scRNAseq datasets containing T cells, and am using Scirpy to find out if this translates to clonal heterogeneity.

Now, as I'm following the Wu dataset analysis using the 0.7 version ( I'm running [these exact lines](https://icbi-lab.github.io/scirpy/latest/tutorials/tutorial_3k_tcr.html#Compute-CDR3-neighborhood-graph-and-define-clonotypes) on the full Wu data), I found a strikingly higher number of clones compared to the presented results. 

Thus, I'm wondering if Scirpy uses dimensional reduction information from the AnnData object (and if so, how) or if this happened by methodological differences to version 0.7. This is rather critical for next steps.

Below, the result after running:

```
ir.pp.ir_dist(adata, n_jobs=11)
ir.tl.define_clonotypes(adata, receptor_arms="all", dual_ir="primary_only")
ir.tl.clonotype_network(adata, min_cells=2)
ir.pl.clonotype_network(
    adata, color="source", base_size=1, show_labels=False, panel_size=(9, 9)
)
```
![image](https://user-images.githubusercontent.com/44589562/144495194-b5f14cf9-b4be-4dd3-86dc-8be6e27ff0c9.png)

**Comment by grst** [comment]
Hi @davisidarta, 

thanks for reaching out! 

> I found a strikingly higher number of clones compared to the presented results.

Sorry, I'm not sure: what other results are you referring to? 

> Thus, I'm wondering if Scirpy uses dimensional reduction information from the AnnData object

For defining clonotypes, scirpy only uses the CDR3 sequence information, and, optionally, the V-genes. 
Information derived from transcriptomics data (in particular the neighborhood graph) are only used for the `tl.clonotype_modularity` feature. 

Best, 
Gregor

**Comment by davisidarta** [comment]
> Sorry, I'm not sure: what other results are you referring to?

[These](https://icbi-lab.github.io/scirpy-paper/wu2020.html), found in Scirpy documentation. 
![image](https://user-images.githubusercontent.com/44589562/144615282-eccf4934-28b8-4402-b005-89108d0ac9e1.png)


> For defining clonotypes, scirpy only uses the CDR3 sequence information, and, optionally, the V-genes.
Information derived from transcriptomics data (in particular the neighborhood graph) are only used for the tl.clonotype_modularity feature.

Thank you for clarifying this point! So most probably the differences I'm seeing are due to changes in Scirpy's internals rather than to my new dim reductions. I'll keep this in mind.

Best,
Davi

**Comment by grst** [comment]
This is likely just a difference in thresholds for the visualization. The plots from that notebook only show clonotypes with >50 cells. 
The actual clonotypes should still be quite similar.
