### ISSUE TITLE
Query epitope databases

### ISSUE THREAD

**Issue by grst** [icbi-lab/scirpy#54]
In GitLab by @grst on Apr 2, 2020, 14:45

null

**Comment by FFinotello** [comment]
A nice model available via immunarch: https://immunarch.com/articles/web_only/v11_db.html

**Comment by FFinotello** [comment]
Hello @grst! 

Besides the three databases listed in the link above (VDJDB, McPAS-TCR, PIRD), other possible resources are:

- IEDB
- The [MAIT reference database](http://www.cbs.dtu.dk/services/MAIT_Match/MAIT_DB_update.php) with invariant CDR3
- The [Adaptive Biotechnology database](www.adaptivebiotech.com/pub/Dean), used to identify (and exclude) public clonotypes shared between unrelated individuals [(Dean et al., 2015)](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-015-0238-z)

**Comment by chris-rands** [comment]
Nice feature idea- could sequence alignment be combined with HLA typing info to improve the predictions?
If HLA type is unknown, could be inferred from scTCR/RNA-seq data potentially (although non-trivial)

**Comment by grst** [comment]
Hi Chris, 

do you have any specific method in mind that predict antigen specificity based on TCR-sequence and HLA-type? 

Also pinging @abyssum, who is one of our (neo-)antigen experts.

**Comment by FFinotello** [comment]
Hi @chris-rands,

Thanks for the suggestion! 

We plan to link our tool to public databases to provide information on the cognate antigen, whenever this info is available.

But considering predictive methods could be a further extension. Any suggestions in this direction?

And yes, HLA-type information predicted from single-cell data (e.g. with [scHLAcount](https://pubmed.ncbi.nlm.nih.gov/32330223/)) would be definitely helpful in this case.

Thanks,
Francesca

**Comment by chris-rands** [comment]
Hi both, rather naively, I was thinking only report/flag alignment matches where the query and target TCR sequence have the same HLA type info to remove/label false positive predictions?

For the query, HLA type info prediction by scHLAcount looks interesting or a tool like arcasHLA for pseudo-bulk style- of course assumes there is (sc)RNA-seq data from the samples

**Comment by grst** [comment]
Another new resource: 
https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkab857/6381136?rss=1

**Comment by grst** [comment]
This is now available in v0.10.0. Matching HLA-types (if available) is possible with the `match_columns` argument of `ir_query`.

**Comment by chris-rands** [comment]
Thanks! I will test it

**Comment by chris-rands** [comment]
It worked well for me, thanks again
